name: Build ESP32 Firmware

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:latest # Official Docker Image

    steps:
    - uses: actions/checkout@v3

    - name: Build Firmware
      run: |
        . $IDF_PATH/export.sh
        idf.py build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: esp32-firmware
        path: |
          build/flasher_args.json
          build/partition_table/partition-table.bin
          build/*.bin
          build/bootloader/bootloader.bin